services:
  webapi:
    image: tuantrannet/webapi:latest
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=TapHoaCoGai;User=sa;Password=Your_password123;Encrypt=False;TrustServerCertificate=True;
    expose:
      - "8080"

  webmvc:
    image: tuantrannet/webmvc:latest
    depends_on:
      - webapi
    environment:
      - API_BASE_URL=http://webapi:8080
    expose:
      - "8080"

  db:
    image: tuantrannet/web_taphoacogai-db:latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./backup:/var/opt/mssql/backup
    command: >
      bash -c "
        /opt/mssql/bin/sqlservr &
        sleep 20 &&
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -i /var/opt/mssql/backup/restore.sql &&
        tail -f /dev/null
      "

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    depends_on:
      - webmvc

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot